create database Warehouse;
use Warehouse;

CREATE TABLE CITIES(
CITY CHAR(20),
STATE CHAR(20),
PRIMARY KEY(CITY)
);

CREATE TABLE WAREHOUSES(
WID INT,
WNAME CHAR(30),
LOCATION CHAR(20),
CITY CHAR(20),
EXTRA_CONTEXT JSON,
PRIMARY KEY (WID),
FOREIGN KEY (CITY) REFERENCES CITIES(CITY)
);

CREATE TABLE STORES(
SID INTEGER,
STORE_NAME CHAR(20),
LOCATION_CITY CHAR(20),
WID INT,
PRIMARY KEY (SID),
FOREIGN KEY (WID) REFERENCES WAREHOUSES(WID)
);

CREATE TABLE CUSTOMER(
CNO INT,
CNAME CHAR(50),
ADDR VARCHAR(50),
CU_CITY CHAR(20),
PRIMARY KEY (CNO)
);

CREATE TABLE ORDERS(
ORDERNO INT,
ODATE DATE,
CNO INTEGER,
PRIMARY KEY (ORDERNO),
FOREIGN KEY (CNO) REFERENCES CUSTOMER(CNO)
);

CREATE TABLE ITEMS(
ITEMNO INT,
DESCR TEXT,
WEIGHT DECIMAL(5,2),
COST DECIMAL(5,2),
PRIMARY KEY (ITEMNO)
);

CREATE TABLE ORDER_DETAILS(
ITEMNO INT,
ORDERNO INT,
ORDERED_QUANTITY INT,
FOREIGN KEY(ITEMNO) REFERENCES ITEMS(ITEMNO),
FOREIGN KEY(ORDERNO) REFERENCES ORDERS(ORDERNO),
PRIMARY KEY (ITEMNO, ORDERNO)
);

CREATE TABLE STORES_ITEMS(
ITEMNO INT,
SID INT,
QUANTITY INTEGER,
FOREIGN KEY(ITEMNO) REFERENCES ITEMS(ITEMNO),
FOREIGN KEY(SID) REFERENCES STORES(SID),
PRIMARY KEY (ITEMNO, SID)
);
